name: open_location_picker
description: FormField to pick one or more locations from open street map
version: 1.1.0
homepage: https://github.com/mo-ah-dawood/open_location_picker

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^5.0.0
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.5


flutter:
