name: open_location_picker
description: FormField to pick one or more locations from open street map
version: 0.2.1
homepage: https://github.com/mo-ah-dawood/open_location_picker

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^2.2.0
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  build_runner: ^2.1.5

flutter:
